### ISSUE TITLE
C2-13242-2

### ISSUE THREAD

**Issue by jack980517** [TheOfficialFloW/DownloadEnabler#4]
Followed the instructions, tried to download a vpk from dropbox, gave me C2-13242-2

**Comment by dizz00** [comment]
You probably write the path under *KERNEL, you should write it under *MAIN. I got the same error and after fixing the path it work for me

**Comment by jack980517** [comment]
No I don't think I got it wrong, but after some time it just mysteriously worked. Who knows why
